import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { basename, join, relative } from 'node:path';
import { parseDoc } from './frontmatter.js';
import type { Studio } from './types.js';

export interface VaultFile {
  path: string;      // absolute
  rel: string;       // relative to vault/
  title: string;
  description: string | null;
}

export function walkVault(studio: Studio): VaultFile[] {
  const vaultRoot = join(studio.root, 'vault');
  const files: VaultFile[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir).sort()) {
      if (entry.startsWith('.')) continue;
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else if (entry.endsWith('.md') && entry !== 'INDEX.md') {
        const { meta, body } = parseDoc(readFileSync(full, 'utf8'));
        const heading = body.match(/^#\s+(.+)$/m)?.[1];
        files.push({
          path: full,
          rel: relative(vaultRoot, full),
          title: heading ?? basename(entry, '.md'),
          description: meta.description ? String(meta.description) : null,
        });
      }
    }
  };
  if (existsSync(vaultRoot)) walk(vaultRoot);
  return files;
}

export function buildIndex(studio: Studio): string {
  const files = walkVault(studio);
  const groups = new Map<string, VaultFile[]>();
  for (const file of files) {
    const dir = file.rel.includes('/') ? file.rel.slice(0, file.rel.lastIndexOf('/')) : '.';
    const list = groups.get(dir) ?? [];
    list.push(file);
    groups.set(dir, list);
  }
  const lines: string[] = [
    '# Vault index',
    '',
    '_Generated by `wr index` — do not edit. One line per file; read the description, open what you need, log what you pulled._',
  ];
  for (const [dir, group] of [...groups.entries()].sort()) {
    lines.push('', `## ${dir === '.' ? 'vault' : dir}`, '');
    for (const file of group) {
      lines.push(`- [${file.title}](${file.rel}) — ${file.description ?? '(no description)'}`);
    }
  }
  const content = lines.join('\n') + '\n';
  writeFileSync(join(studio.root, 'vault', 'INDEX.md'), content);
  return content;
}

export interface FindHit {
  path: string;   // relative to vault/
  line: number;
  text: string;
  score: number;
}

export function findInVault(studio: Studio, query: string): FindHit[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return [];
  const hits: FindHit[] = [];
  for (const file of walkVault(studio)) {
    const lines = readFileSync(file.path, 'utf8').split('\n');
    const nameBoost = terms.some((t) => file.rel.toLowerCase().includes(t)) ? 3 : 0;
    lines.forEach((text, idx) => {
      const lower = text.toLowerCase();
      const matched = terms.filter((t) => lower.includes(t));
      if (matched.length === 0) return;
      const headingBoost = /^#{1,6}\s/.test(text) ? 2 : 0;
      hits.push({
        path: file.rel,
        line: idx + 1,
        text: text.trim().slice(0, 160),
        score: matched.length + nameBoost + headingBoost,
      });
    });
  }
  return hits.sort((a, b) => b.score - a.score).slice(0, 30);
}

export function resolveLinks(
  studio: Studio,
  filePath: string,
): { out: string[]; broken: string[] } {
  const files = walkVault(studio);
  const byName = new Map<string, VaultFile>();
  for (const file of files) byName.set(basename(file.rel, '.md').toLowerCase(), file);
  const text = readFileSync(filePath, 'utf8');
  const out: string[] = [];
  const broken: string[] = [];
  for (const match of text.matchAll(/\[\[([^\]|#]+)(?:[|#][^\]]*)?\]\]/g)) {
    const name = match[1].trim().toLowerCase();
    const target = byName.get(name);
    if (target) out.push(target.rel);
    else broken.push(match[1].trim());
  }
  return { out: [...new Set(out)], broken: [...new Set(broken)] };
}
